module.exports = [
  '7 Days to Die',
  'A Plague Tale: Innocence',
  'Absolver',
  'ACE COMBAT™ 7: SKIES UNKNOWN',
  'Age of Wonders III',
  'Age of Wonders: Planetfall',
  'AI: The Somnium Files',
  'Aion™',
  'Albino Lullaby: Episode 1',
  'Albion Online',
  'Amazing Cultivation Simulator / 了不起的修仙模拟器',
  'American Truck Simulator',
  'Ancestors Legacy',
  'Anno 1800™',
  'Anno 1800™',
  'Anno 1800™',
  'AO International Tennis',
  'Apex Legends™',
  'Apollo 11 Lunar Landing Demo',
  'Argo',
  'ARK: Survival Evolved',
  'ARK: Survival Of The Fittest',
  'Arma 3',
  'Armello',
  'Armored Warfare',
  'Artifact',
  'Assassin’s Creed® III Remastered',
  'Assassin’s Creed® IV Black Flag™',
  'Assassin’s Creed® IV Black Flag™',
  'Assassin’s Creed® Odyssey',
  'Assassin’s Creed® Odyssey',
  'Assassin’s Creed® Origins',
  'Assassin’s Creed® Origins',
  'Assassin’s Creed® Unity',
  'Assassin’s Creed® Unity',
  'Assassin’s Creed®: Syndicate',
  'Assassin’s Creed®: Syndicate',
  'Assetto Corsa',
  'Assetto Corsa Competizione',
  'Asterix & Obelix XXL 3 - The Crystal Menhir',
  'ASTRONEER',
  'ATLAS',
  'ATOM RPG',
  'ATOMEGA™',
  'AVICII Invector',
  'Batman™: Arkham Asylum Game of the Year Edition',
  'Batman™: Arkham City - Game of the Year Edition',
  'Batman™: Arkham Knight',
  'Batman™: Arkham Origins',
  'Battlefleet Gothic: Armada 2',
  'Battlerite',
  'Battlerite Royale',
  'Battletech',
  'BeamNG.drive',
  'Bear With Me: The Lost Robots',
  'Besiege',
  'BioShock Infinite',
  'BioShock™ 2 Remastered',
  'BioShock™ Remastered',
  'Black Desert Online',
  "Black Future '88",
  'Black Squad',
  'BLACKSAD: Under the Skin',
  'Blackwake',
  'Blair Witch',
  'BlazBlue: Cross Tag Battle',
  'Blizzard® Battle.net®',
  'Borderlands 2',
  'Borderlands 3',
  'Borderlands Game of the Year Enhanced',
  'Borderlands: The Pre-Sequel',
  'Brawlhalla',
  'Brothers: A Tale of Two Sons',
  'Call of Cthulhu®',
  'Call of Duty: World at War',
  'Call of Duty® 4: Modern Warfare®',
  'Call of Duty®: Black Ops 4',
  'Call of Duty®: Black Ops III',
  'Call of Duty®: Infinite Warfare',
  'Call of Duty®: Modern Warfare®',
  'Call of Duty®: Modern Warfare® 2 Multiplayer',
  'Call of Duty®: Modern Warfare® 2 Singleplayer',
  'Call of Duty®: Modern Warfare® 3 Multiplayer',
  'Call of Duty®: Modern Warfare® 3 singleplayer',
  'Call of Duty®: WWII',
  'CS:GO',
  'LoL',
  'WoW',
  'Dota 2',
  'CardLife: Cardboard Survival',
  'Catherine Classic',
  'Celeste',
  'Chernobylite',
  'Chivalry: Medieval Warfare',
  'Cities: Skylines',
  'Claybook',
  'Clicker Heroes',
  'Clicker Heroes 2',
  'Closers',
  'Commandos 2 - HD Remaster',
  'Company of Heroes',
  'Conan Exiles',
  'Conception PLUS: Maidens of the Twelve Stars',
  'Construction Simulator 2 US - Pocket Edition',
  'Constructor Plus',
  'Cooking Simulator',
  'Counter-Strike',
  'Counter-Strike: Global Offensive',
  'Counter-Strike: Source',
  'Crash Bandicoot™ N. Sane Trilogy',
  'Crossfire',
  'Crossout',
  'Crusader Kings II',
  'Crying Suns',
  'Cuisine Royale',
  'Cultist Simulator',
  'Cuphead',
  'Dakar 18',
  'DARK SOULS™ II',
  'DARK SOULS™ II: Scholar of the First Sin',
  'DARK SOULS™ III',
  'DARK SOULS™: REMASTERED',
  'Darkest Dungeon®',
  'Darksiders II Deathinitive Edition',
  'Darksiders III',
  'DARKSIDERS: GENESIS',
  'Darwin Project',
  'Dauntless',
  'Dawn of Man',
  'DayZ',
  'Dead by Daylight',
  'Dead Cells',
  'Dead Frontier 2',
  'Dead In Vinland',
  'Deceit',
  'Deep Rock Galactic',
  'Deep Sky Derelicts',
  'Deliver Us The Moon: Fortuna',
  'Depth',
  'Descenders',
  'DESOLATE',
  'Destiny 2',
  'Diablo III',
  'Diesel Brothers: Truck Building Simulator',
  'DiRT 3 Complete Edition',
  'DiRT 4',
  'DiRT Rally 2.0',
  'Dirty Bomb®',
  'Disco Elysium',
  'Dishonored',
  'Dishonored 2',
  'Dishonored®: Death of the Outsider™',
  'Distance',
  'Divinity: Original Sin 2',
  "Don't Starve",
  "Don't Starve Together",
  'Donut County',
  'DOOM®',
  'Dota 2',
  'Dota Underlords',
  'Double Turn',
  'Dragon Nest',
  'Dungreed',
  'DUSK',
  'Dying Light',
  'Dying Light: Bad Blood',
  'EARTH DEFENSE FORCE 5',
  'Edge Of Eternity',
  'ELEX',
  'Elite Dangerous',
  'Empyrion - Galactic Survival',
  'Endless Space® 2',
  'Enter the Gungeon',
  'Euro Truck Simulator 2',
  'Europa Universalis IV',
  'EVE Online',
  'Everreach: Project Eden',
  'EVERSPACE™',
  'EXAPUNKS',
  'F1® 2018',
  'F1® 2019 Anniversary Edition',
  'F1™ 2017',
  'Factorio',
  'Fade to Silence',
  'Fallout 3: Game of the Year Edition',
  'Fallout 76',
  'Fallout: New Vegas',
  'Far Cry® 4',
  'Far Cry® 4',
  'Far Cry® 5',
  'Far Cry® 5',
  'Far Cry® New Dawn',
  'Far Cry® New Dawn',
  'Far Cry® Primal',
  'Far Cry® Primal',
  'FAR: Lone Sails',
  'Farm Together',
  'Farming Simulator 17',
  'Farming Simulator 19',
  'Fear The Wolves',
  'FIA European Truck Racing Championship',
  'Fimbul',
  'Firewatch',
  "Five Nights at Freddy's",
  "Five Nights at Freddy's 2",
  'Football Manager 2018',
  'Football Manager 2019',
  'Football Manager Touch 2018',
  'For Honor™',
  'For Honor™',
  'Forager',
  'Forged Battalion',
  'Fortnite',
  'Foundation',
  'Fractured Lands',
  'Friday the 13th: The Game',
  'FrostPunk',
  'FrostRunner',
  'FTL: Faster Than Light',
  "Garry's Mod",
  'Generation Zero',
  'Gloomhaven',
  'Golf With Your Friends',
  'Gravel',
  'GreedFall',
  'Green Hell',
  'Grim Dawn',
  'GRIP: Combat Racing',
  'GTFO',
  'Guacamelee! 2',
  'Guild Wars 2',
  'GUILTY GEAR Xrd -REVELATOR-',
  'Hacknet',
  'Half-Life®',
  'Half-Life® 2',
  'Hearthstone: Heroes of Warcraft',
  'Hearts of Iron IV',
  'Hell Let Loose',
  "Hellblade: Senua's Sacrifice",
  'Heroes of Newerth',
  'Heroes of the Storm',
  'HITMAN™',
  'HITMAN™2',
  'Hobo: Tough Life',
  'Holdfast: Nations At War',
  'Hollow Knight',
  'Homefront®: The Revolution',
  'Hot Lava',
  'House Flipper',
  'Human: Fall Flat',
  'Hunt: Showdown',
  'I’m not a Monster',
  "Ice Age: Scrat's Nutty Adventure",
  'Idle Champions of the Forgotten Realms',
  'Immortal: Unchained',
  'Imperator: Rome',
  'Infliction',
  'Injustice™ 2',
  'INSOMNIA: The Ark',
  'Insurgency',
  'Insurgency: Sandstorm',
  'Into the Breach',
  'Islands of Nyne: Battle Royale',
  'Jurassic World Evolution™',
  'Kenshi',
  'Kerbal Space Program',
  'Killing Floor 2',
  'Kingdom Come: Deliverance',
  'Kingdom Rush Origins',
  'Kingdom Two Crowns',
  'KurtzPel',
  'Last Tide',
  'League of Legends',
  'Left 4 Dead 2',
  'LEGO® Batman 2 DC Super Heroes™',
  'LEGO® Batman: The Videogame',
  'LEGO® Batman™ 3: Beyond Gotham',
  'LEGO® DC Super-Villains',
  'LEGO® Harry Potter: Years 1-4',
  'LEGO® Jurassic World',
  'LEGO® Marvel Super Heroes 2',
  "LEGO® MARVEL's Avengers",
  'LEGO® Marvel™ Super Heroes',
  'LEGO® The Incredibles',
  'LEGO® Worlds',
  "Leisure Suit Larry - Wet Dreams Don't Dry",
  'Lethal League Blaze',
  'Lineage® II',
  'Little Big Workshop',
  'Lonely Mountains: Downhill',
  'Mad Max',
  'Mafia III',
  'Magic the Gathering: Arena',
  'Mechwarrior 5: Mercenaries',
  'MEG 9: Lost Echoes',
  'Men of War: Assault Squad 2',
  'Metro 2033 Redux',
  'Metro Exodus',
  'Metro Exodus',
  'Metro: Last Light Redux',
  'Middle-earth™: Shadow of Mordor™',
  'Middle-earth™: Shadow of War™',
  'Minecraft: Java Version',
  'Minion Masters',
  'Miracle snack shop',
  'Monster Energy Supercross - The Official Videogame 2',
  'Monster Energy Supercross - The Official Videogame 3',
  'Moonlighter',
  'Moons of Madness™',
  'MORDHAU',
  'Mortal Kombat 11',
  'Mortal Kombat X',
  'Mosaic',
  'MOTHERGUNSHIP',
  'MotoGP™19',
  'Mount & Blade',
  'Mount & Blade: Warband',
  'MUSYNX',
  'Mutant Year Zero: Road to Eden',
  'MXGP 2019 - The Official Motocross Videogame',
  'My Memory of Us',
  'My Time at Portia',
  'Myst III: Exile',
  'Myst IV: Revelation',
  'Myst V: End of Ages',
  'Myst® Masterpiece Edition',
  'Narcosis',
  'NASCAR Heat 3',
  'NBA 2K Playgrounds 2',
  'NBA 2K17',
  'NBA 2K18',
  'NBA 2K19',
  'Nex Machina',
  'Next Day: Survival',
  "No Man's Sky",
  'Orwell: Keeping an Eye On You',
  'Out of the Park Baseball 19',
  'Outlast',
  'Outward',
  'Overcooked 2',
  "OVERKILL's The Walking Dead",
  'Overland',
  'Overwatch',
  'Owlboy',
  'Oxygen Not Included',
  'Paladins®',
  'Papers, Please',
  'Parkitect',
  'Past Cure',
  'Path of Exile',
  'Pathfinder: Kingmaker® - Enhanced Edition',
  'Pax Nova',
  'PAYDAY 2: Ultimate Edition',
  'PC Building Simulator',
  'Phantom Doctrine',
  'Pillars of Eternity',
  'Pillars of Eternity II: Deadfire',
  'PixARK',
  'Plane Mechanic Simulator',
  'PLANET ALPHA',
  'Planet Coaster®',
  'Planet Zoo',
  'PlanetSide 2',
  'Planetside Arena',
  "PLAYERUNKNOWN'S BATTLEGROUNDS",
  "PLAYERUNKNOWN'S BATTLEGROUNDS Test Server",
  'Portal 2',
  'Portal™',
  'Post Scriptum',
  'Praetorians - HD Remaster',
  'Praey for the Gods',
  'Prey®',
  'Project CARS',
  'Project CARS 2',
  'Project Winter',
  'PUBG: Closed Experimental Server',
  'Pummel Party',
  'Pure Farming 2018',
  'Pyre',
  'Q.U.B.E. 2',
  'Quake II RTX',
  'Quake® Champions',
  'Race With Ryan',
  'RAD',
  'Raft',
  'RAGE 2',
  'RAGE 2',
  'RAID: World War II',
  'Ravenfield',
  'Realm Grinder',
  'Realm Royale',
  'realMyst: Masterpiece Edition',
  'Reigns: Game of Thrones',
  'Remnant: From the Ashes',
  'Rend',
  'RIDE 3',
  'RiME',
  'RimWorld',
  'Risen 3 - Titan Lords',
  'Rising Storm 2: Vietnam',
  'Riven: The Sequel to MYST',
  'Rocket League®',
  'Rugby 20',
  'Russian Fishing 4',
  'Rust',
  'Sacred 3',
  'Salt and Sanctuary',
  'SCP: Secret Laboratory',
  'SCUM',
  'Sekiro™: Shadows Die Twice',
  'Semblance',
  'Session: Skateboarding Sim Game',
  'Shadow Warrior 2',
  'Shadowrun Returns',
  'Shenmue I & II',
  'Shenmue III',
  'Sid Meier’s Civilization® VI',
  "Sid Meier's Civilization® V",
  'Silver Chains',
  'Skybolt Zack',
  'Slay the Spire',
  'SMITE®',
  'Sniper Elite 3',
  'Sniper Elite 4',
  'Sniper Elite V2 Remastered',
  'SOMA',
  'Sonic Forces',
  'Sonic Mania',
  'SOULCALIBUR™ VI',
  'SoulWorker',
  'Space Engineers',
  'Space Hulk: Tactics',
  'Spacelords',
  'SpellForce 3',
  'SpellForce 3: Soul Harvest',
  'Spintires: MudRunner',
  'Splitgate: Arena Warfare',
  'SpyParty',
  'Spyro™ Reignited Trilogy',
  'Squad',
  'Star Control®: Origins',
  'Star Wars: Battlefront 2 (Classic, 2005)',
  'STAR WARS™ - Knights of the Old Republic™',
  'Starbound',
  'StarCraft II®',
  'StarCraft® Remastered',
  'Stardew Valley',
  'Startup Company',
  'Steam®',
  'Stellaris',
  'Still There',
  'Strange Brigade',
  'Subnautica',
  'Subnautica: Below Zero',
  'Sundered',
  'Sunset Overdrive',
  'Super Mega Baseball 2',
  'Surviving Mars',
  'Switchblade',
  'Tabletop Simulator',
  'Tacoma',
  'Team Fortress 2',
  'Team Sonic Racing™',
  'TEKKEN 7',
  'TERA',
  'Terminator: Resistance',
  'Terraria',
  "The Bard's Tale IV",
  'The Bradwell Conspiracy',
  'The Crew® 2',
  'The Crew® 2',
  'The Crew™',
  'The Crew™',
  'The D.R.G. Initiative',
  'The Darkness II',
  'The Elder Scrolls V: Skyrim',
  'The Elder Scrolls V: Skyrim Special Edition',
  'The Elder Scrolls® Online: Elsweyr',
  'The Evil Within 2',
  'The Fisherman - Fishing Planet',
  'The Forest',
  'The Golf Club™ 2019 featuring PGA TOUR',
  'The Isle',
  'The Jackbox Party Pack 3',
  "THE KING OF FIGHTERS '98 ULTIMATE MATCH FINAL EDITION",
  'The Legend of Bum-Bo',
  'The Legend of Heroes: Trails of Cold Steel',
  'The LEGO® Movie - Videogame',
  'The LEGO® Movie 2 Videogame',
  'The LEGO® NINJAGO® Movie Video Game',
  'The Long Dark',
  'The Surge',
  'The Surge 2',
  'The Walking Dead: The Final Season',
  'The Witcher 2: Assassins of Kings Enhanced Edition',
  'The Witcher® 3: Wild Hunt',
  'The Witness',
  'theHunter: Call of the Wild™',
  'They Are Billions',
  'Thief Simulator',
  'This War of Mine',
  'Thronebreaker: The Witcher Tales',
  'Tom Clancy’s Ghost Recon Breakpoint',
  'Tom Clancy’s The Division® 2',
  'Tom Clancy’s The Division® 2',
  "Tom Clancy's Ghost Recon® Wildlands",
  "Tom Clancy's Ghost Recon® Wildlands",
  "Tom Clancy's Rainbow Six® Siege",
  "Tom Clancy's Rainbow Six® Siege",
  "Tom Clancy's Rainbow Six® Siege - Technical Test Server",
  "Tom Clancy's The Division™",
  "Tom Clancy's The Division™",
  'Torchlight II',
  'Total War: THREE KINGDOMS',
  'Totally Accurate Battle Simulator',
  'Totally Accurate Battlegrounds',
  'Tower of Time',
  'Transport Fever',
  'Transport Fever 2',
  'Tree of Savior',
  'Trials® Rising',
  'Trials® Rising',
  'Tricky Towers',
  'Trine 4: The Nightmare Prince',
  'Triton Survival',
  'Tropico 6',
  'Trove',
  'Trover Saves The Universe',
  'TT Isle of Man',
  'Two Point Hospital',
  'Ultimate Fishing Simulator',
  'Underworld Ascendant®',
  'Unknown Fate',
  'Unturned',
  'URU: Complete Chronicles',
  'Valkyria Chronicles 4',
  'Vampyr',
  'Vanquish',
  'V-Rally 4',
  'War of Rights',
  'War Thunder',
  'War Thunder',
  'Warframe',
  'Warhammer 40,000: Inquisitor - Martyr',
  'Warhammer 40,000: Inquisitor - Prophecy',
  'Warhammer 40,000: Mechanicus',
  'Warhammer: Chaosbane',
  'Warhammer: End Times - Vermintide',
  'Warhammer: Vermintide 2',
  'WARRIORS OROCHI 4',
  'Watch_Dogs® 2',
  'Watch_Dogs® 2',
  'Watch_Dogs™',
  'Watch_Dogs™',
  'We Happy Few',
  'Welcome to the Game II',
  'Will To Live Online',
  'Wolfenstein® II: The New Colossus™',
  'Wolfenstein®: The New Order',
  'Wolfenstein®: The Old Blood™',
  'Wolfenstein®: Youngblood',
  'Wolfenstein®: Youngblood',
  'World of Tanks',
  'World of Tanks: Blitz',
  'World of Warcraft Classic',
  'World of Warcraft: Battle for Azeroth',
  'World of Warships',
  'World of Warships',
  'World War 3',
  'World War Z',
  'Worms W.M.D',
  'Wreckfest',
  'WWE 2K19',
  'WWE 2K20',
  'Wytchsun: Elleros Origins',
  'X4: Foundations',
  'XCOM® 2',
  'XERA: Survival',
  'Yakuza 0',
  'Yakuza Kiwami',
  "Yoku's Island Express",
  'Yooka-Laylee',
  'Yooka-Laylee and the Impossible Lair',
  'Ys VIII: Lacrimosa of DANA',
  'Z1 Battle Royale',
  '太吾绘卷 - The Scroll Of Taiwu',
];
